apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/santosh-gh/k8s-17-deployment.git
    targetRevision: HEAD
    path: multi-manifests/rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: multi-manifests2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true