apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
    targetRevision: HEAD
    path: kustomize-manifests/config/base
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true