apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
    targetRevision: HEAD
    path: apps-kustomize-manifests-prod/microservices
    directory:
      recurse: true   # ensures all child application YAMLs inside are applied
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
