apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-manifets
  namespace: argocd
spec:
  generators:
  - git: 
      repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
      revision: HEAD
      directories:  
      - path: multi-manifests/*
  
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server:  https://kubernetes.default.svc
        namespace:  multi-manifets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true