apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: single-manifets
  namespace: argocd
spec:
  generators:
  - list:
      elements:  
        - namespace: dev
        - namespace: test
        - namespace: prod
  template:
    metadata:
      name: '{{ namespace }}-single-manifets'
    spec:
      project: default
      source:
        repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
        targetRevision: HEAD
        path: single-manifests
      destination:
        server:  https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true